# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  devcapacitywebapp:
    image: devcapacitywebapp
    build:
      context: .
      dockerfile: DevCapacityWebApp/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5084:5084
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
